services:
  app:
    image: ghcr.io/ferilee/tsabita:latest
    container_name: tsabita
    ports:
      - "127.0.0.1:3010:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_FILE_NAME: /app/data/tsabita.sqlite
    volumes:
      - /srv/data/tsabita/sqlite:/app/data
    networks:
      - ferileenet
    restart: always

networks:
  ferileenet:
    external: true
